sensors:
  - default_sensor
default_sensor:
  filtered_cloud_topic: sim_camera
  max_range: 5.0
  max_update_rate: 1.0
  padding_offset: 0.1
  padding_scale: 1.0
  point_cloud_topic: /camera/depth/color/points
  point_subsample: 1
  # sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
  # Occupancy map monitoring temporarily disabled. To re-enable, restore the line above
  # or set this to the desired plugin.
  sensor_plugin: ""